[tool.poetry]
name = "nemo-fin-scrap"
version = "0.1.0"
description = ""
authors = ["luismaiabr.np550xda <luismaiasombra@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
